
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.20.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace CSLab13 {
    using System;
    using Terminal.Gui;
    
    
    public partial class MyDialog : Terminal.Gui.Window {
        
        private Terminal.Gui.ColorScheme greyOnBlack;
        
        private Terminal.Gui.FrameView score;
        
        private Terminal.Gui.TableView tableView;
        
        private Terminal.Gui.Button print;
        
        private Terminal.Gui.Button quit;
        
        private void InitializeComponent() {
            this.quit = new Terminal.Gui.Button();
            this.print = new Terminal.Gui.Button();
            this.tableView = new Terminal.Gui.TableView();
            this.score = new Terminal.Gui.FrameView();
            this.greyOnBlack = new Terminal.Gui.ColorScheme();
            this.greyOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.greyOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Black, Terminal.Gui.Color.DarkGray);
            this.greyOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.DarkGray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.BorderBrush = Terminal.Gui.Color.Blue;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "";
            this.score.Width = 24;
            this.score.Height = 16;
            this.score.X = 3;
            this.score.Y = 1;
            this.score.ColorScheme = this.greyOnBlack;
            this.score.Data = "score";
            this.score.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.score.Border.BorderBrush = Terminal.Gui.Color.Black;
            this.score.Border.Effect3D = false;
            this.score.Border.Effect3DBrush = null;
            this.score.Border.DrawMarginFrame = true;
            this.score.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.score.Title = "Результати";
            this.Add(this.score);
            this.tableView.Width = 80;
            this.tableView.Height = 14;
            this.tableView.X = 0;
            this.tableView.Y = 0;
            this.tableView.Data = "tableView";
            this.tableView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.tableView.FullRowSelect = false;
            this.tableView.Style.AlwaysShowHeaders = false;
            this.tableView.Style.ExpandLastColumn = true;
            this.tableView.Style.InvertSelectedCellFirstCharacter = false;
            this.tableView.Style.ShowHorizontalHeaderOverline = true;
            this.tableView.Style.ShowHorizontalHeaderUnderline = true;
            this.tableView.Style.ShowVerticalCellLines = true;
            this.tableView.Style.ShowVerticalHeaderLines = true;
            System.Data.DataTable tableViewTable;
            tableViewTable = new System.Data.DataTable();
            System.Data.DataColumn tableViewTableColumn0;
            tableViewTableColumn0 = new System.Data.DataColumn();
            tableViewTableColumn0.ColumnName = "Column 0";
            tableViewTable.Columns.Add(tableViewTableColumn0);
            System.Data.DataColumn tableViewTableColumn1;
            tableViewTableColumn1 = new System.Data.DataColumn();
            tableViewTableColumn1.ColumnName = "Column 1";
            tableViewTable.Columns.Add(tableViewTableColumn1);
            System.Data.DataColumn tableViewTableColumn2;
            tableViewTableColumn2 = new System.Data.DataColumn();
            tableViewTableColumn2.ColumnName = "Column 2";
            tableViewTable.Columns.Add(tableViewTableColumn2);
            System.Data.DataColumn tableViewTableColumn3;
            tableViewTableColumn3 = new System.Data.DataColumn();
            tableViewTableColumn3.ColumnName = "Column 3";
            tableViewTable.Columns.Add(tableViewTableColumn3);
            this.tableView.Table = tableViewTable;
            this.score.Add(this.tableView);
            this.print.Width = 12;
            this.print.Height = 1;
            this.print.X = 3;
            this.print.Y = 17;
            this.print.ColorScheme = this.greyOnBlack;
            this.print.Data = "print";
            this.print.Text = "Друк";
            this.print.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.print.IsDefault = false;
            this.Add(this.print);
            this.quit.Width = 12;
            this.quit.Height = 1;
            this.quit.X = 15;
            this.quit.Y = 17;
            this.quit.ColorScheme = this.greyOnBlack;
            this.quit.Data = "quit";
            this.quit.Text = "Вийти";
            this.quit.TextAlignment = Terminal.Gui.TextAlignment.Centered;
            this.quit.IsDefault = false;
            this.Add(this.quit);
        }
    }
}
